/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TripVault API
 * Travel manager API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { axiosInstance } from './axios';
export interface RegisterDto {
  name: string;
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface CreateTripDto {
  title: string;
  description?: string;
  startDate?: string;
  endDate?: string;
}

export interface UpdateTripDto {
  title?: string;
  description?: string;
  startDate?: string;
  endDate?: string;
}

export interface CreatePlaceDto {
  name: string;
  description?: string;
  address?: string;
  date?: string;
}

export type CreateExpenseDtoCategory =
  (typeof CreateExpenseDtoCategory)[keyof typeof CreateExpenseDtoCategory];

export const CreateExpenseDtoCategory = {
  accommodation: 'accommodation',
  transport: 'transport',
  food: 'food',
  activities: 'activities',
  other: 'other',
} as const;

export interface CreateExpenseDto {
  title: string;
  amount: number;
  category: CreateExpenseDtoCategory;
  date?: string;
}

export interface InviteMemberDto {
  email: string;
}

export type UpdateMemberRoleDtoRole =
  (typeof UpdateMemberRoleDtoRole)[keyof typeof UpdateMemberRoleDtoRole];

export const UpdateMemberRoleDtoRole = {
  owner: 'owner',
  viewer: 'viewer',
} as const;

export interface UpdateMemberRoleDto {
  role: UpdateMemberRoleDtoRole;
}

export const appControllerGetHello = (signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1`, method: 'GET', signal });
};

export const getAppControllerGetHelloQueryKey = () => {
  return [`/api/v1`] as const;
};

export const getAppControllerGetHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) =>
    appControllerGetHello(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetHello>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetHelloQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHello>>
>;
export type AppControllerGetHelloQueryError = unknown;

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<typeof appControllerGetHello>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAppControllerGetHelloQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const authControllerRegister = (registerDto: RegisterDto, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerDto,
    signal,
  });
};

export const getAuthControllerRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationKey = ['authControllerRegister'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegister>>,
    { data: RegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>;
export type AuthControllerRegisterMutationBody = RegisterDto;
export type AuthControllerRegisterMutationError = unknown;

/**
 * @summary Register a new user
 */
export const useAuthControllerRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegister>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  return useMutation(getAuthControllerRegisterMutationOptions(options), queryClient);
};

/**
 * @summary Login and receive JWT token
 */
export const authControllerLogin = (loginDto: LoginDto, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginDto,
    signal,
  });
};

export const getAuthControllerLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ['authControllerLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = unknown;

/**
 * @summary Login and receive JWT token
 */
export const useAuthControllerLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogin>>,
      TError,
      { data: LoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
};

/**
 * @summary Create a new trip
 */
export const tripsControllerCreate = (createTripDto: CreateTripDto, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createTripDto,
    signal,
  });
};

export const getTripsControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tripsControllerCreate>>,
    TError,
    { data: CreateTripDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tripsControllerCreate>>,
  TError,
  { data: CreateTripDto },
  TContext
> => {
  const mutationKey = ['tripsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tripsControllerCreate>>,
    { data: CreateTripDto }
  > = (props) => {
    const { data } = props ?? {};

    return tripsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TripsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tripsControllerCreate>>
>;
export type TripsControllerCreateMutationBody = CreateTripDto;
export type TripsControllerCreateMutationError = unknown;

/**
 * @summary Create a new trip
 */
export const useTripsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tripsControllerCreate>>,
      TError,
      { data: CreateTripDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tripsControllerCreate>>,
  TError,
  { data: CreateTripDto },
  TContext
> => {
  return useMutation(getTripsControllerCreateMutationOptions(options), queryClient);
};

/**
 * @summary Get all my trips
 */
export const tripsControllerFindAll = (signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips`, method: 'GET', signal });
};

export const getTripsControllerFindAllQueryKey = () => {
  return [`/api/v1/trips`] as const;
};

export const getTripsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tripsControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindAll>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTripsControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tripsControllerFindAll>>> = ({ signal }) =>
    tripsControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tripsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TripsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tripsControllerFindAll>>
>;
export type TripsControllerFindAllQueryError = unknown;

export function useTripsControllerFindAll<
  TData = Awaited<ReturnType<typeof tripsControllerFindAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTripsControllerFindAll<
  TData = Awaited<ReturnType<typeof tripsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTripsControllerFindAll<
  TData = Awaited<ReturnType<typeof tripsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all my trips
 */

export function useTripsControllerFindAll<
  TData = Awaited<ReturnType<typeof tripsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTripsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get trip details
 */
export const tripsControllerFindOne = (id: string, signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips/${id}`, method: 'GET', signal });
};

export const getTripsControllerFindOneQueryKey = (id: string) => {
  return [`/api/v1/trips/${id}`] as const;
};

export const getTripsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof tripsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindOne>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTripsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tripsControllerFindOne>>> = ({ signal }) =>
    tripsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tripsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TripsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof tripsControllerFindOne>>
>;
export type TripsControllerFindOneQueryError = unknown;

export function useTripsControllerFindOne<
  TData = Awaited<ReturnType<typeof tripsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTripsControllerFindOne<
  TData = Awaited<ReturnType<typeof tripsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tripsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tripsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTripsControllerFindOne<
  TData = Awaited<ReturnType<typeof tripsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get trip details
 */

export function useTripsControllerFindOne<
  TData = Awaited<ReturnType<typeof tripsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tripsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTripsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update trip (owner only)
 */
export const tripsControllerUpdate = (
  id: string,
  updateTripDto: UpdateTripDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateTripDto,
    signal,
  });
};

export const getTripsControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tripsControllerUpdate>>,
    TError,
    { id: string; data: UpdateTripDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tripsControllerUpdate>>,
  TError,
  { id: string; data: UpdateTripDto },
  TContext
> => {
  const mutationKey = ['tripsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tripsControllerUpdate>>,
    { id: string; data: UpdateTripDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return tripsControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TripsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tripsControllerUpdate>>
>;
export type TripsControllerUpdateMutationBody = UpdateTripDto;
export type TripsControllerUpdateMutationError = unknown;

/**
 * @summary Update trip (owner only)
 */
export const useTripsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tripsControllerUpdate>>,
      TError,
      { id: string; data: UpdateTripDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tripsControllerUpdate>>,
  TError,
  { id: string; data: UpdateTripDto },
  TContext
> => {
  return useMutation(getTripsControllerUpdateMutationOptions(options), queryClient);
};

/**
 * @summary Delete trip (owner only)
 */
export const tripsControllerRemove = (id: string, signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips/${id}`, method: 'DELETE', signal });
};

export const getTripsControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tripsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tripsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['tripsControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tripsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return tripsControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type TripsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof tripsControllerRemove>>
>;

export type TripsControllerRemoveMutationError = unknown;

/**
 * @summary Delete trip (owner only)
 */
export const useTripsControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tripsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tripsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getTripsControllerRemoveMutationOptions(options), queryClient);
};

/**
 * @summary Add a place to a trip
 */
export const placesControllerCreate = (
  tripId: string,
  createPlaceDto: CreatePlaceDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/places`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPlaceDto,
    signal,
  });
};

export const getPlacesControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placesControllerCreate>>,
    TError,
    { tripId: string; data: CreatePlaceDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof placesControllerCreate>>,
  TError,
  { tripId: string; data: CreatePlaceDto },
  TContext
> => {
  const mutationKey = ['placesControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof placesControllerCreate>>,
    { tripId: string; data: CreatePlaceDto }
  > = (props) => {
    const { tripId, data } = props ?? {};

    return placesControllerCreate(tripId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlacesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof placesControllerCreate>>
>;
export type PlacesControllerCreateMutationBody = CreatePlaceDto;
export type PlacesControllerCreateMutationError = unknown;

/**
 * @summary Add a place to a trip
 */
export const usePlacesControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof placesControllerCreate>>,
      TError,
      { tripId: string; data: CreatePlaceDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof placesControllerCreate>>,
  TError,
  { tripId: string; data: CreatePlaceDto },
  TContext
> => {
  return useMutation(getPlacesControllerCreateMutationOptions(options), queryClient);
};

/**
 * @summary Get all places in a trip
 */
export const placesControllerFindAll = (tripId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips/${tripId}/places`, method: 'GET', signal });
};

export const getPlacesControllerFindAllQueryKey = (tripId: string) => {
  return [`/api/v1/trips/${tripId}/places`] as const;
};

export const getPlacesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof placesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof placesControllerFindAll>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlacesControllerFindAllQueryKey(tripId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof placesControllerFindAll>>> = ({
    signal,
  }) => placesControllerFindAll(tripId, signal);

  return { queryKey, queryFn, enabled: !!tripId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof placesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlacesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof placesControllerFindAll>>
>;
export type PlacesControllerFindAllQueryError = unknown;

export function usePlacesControllerFindAll<
  TData = Awaited<ReturnType<typeof placesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof placesControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof placesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof placesControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlacesControllerFindAll<
  TData = Awaited<ReturnType<typeof placesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof placesControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof placesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof placesControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlacesControllerFindAll<
  TData = Awaited<ReturnType<typeof placesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof placesControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all places in a trip
 */

export function usePlacesControllerFindAll<
  TData = Awaited<ReturnType<typeof placesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof placesControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPlacesControllerFindAllQueryOptions(tripId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a place
 */
export const placesControllerRemove = (tripId: string, id: string, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/places/${id}`,
    method: 'DELETE',
    signal,
  });
};

export const getPlacesControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placesControllerRemove>>,
    TError,
    { tripId: string; id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof placesControllerRemove>>,
  TError,
  { tripId: string; id: string },
  TContext
> => {
  const mutationKey = ['placesControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof placesControllerRemove>>,
    { tripId: string; id: string }
  > = (props) => {
    const { tripId, id } = props ?? {};

    return placesControllerRemove(tripId, id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlacesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof placesControllerRemove>>
>;

export type PlacesControllerRemoveMutationError = unknown;

/**
 * @summary Delete a place
 */
export const usePlacesControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof placesControllerRemove>>,
      TError,
      { tripId: string; id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof placesControllerRemove>>,
  TError,
  { tripId: string; id: string },
  TContext
> => {
  return useMutation(getPlacesControllerRemoveMutationOptions(options), queryClient);
};

/**
 * @summary Add an expense to a trip
 */
export const expensesControllerCreate = (
  tripId: string,
  createExpenseDto: CreateExpenseDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/expenses`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createExpenseDto,
    signal,
  });
};

export const getExpensesControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesControllerCreate>>,
    TError,
    { tripId: string; data: CreateExpenseDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesControllerCreate>>,
  TError,
  { tripId: string; data: CreateExpenseDto },
  TContext
> => {
  const mutationKey = ['expensesControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesControllerCreate>>,
    { tripId: string; data: CreateExpenseDto }
  > = (props) => {
    const { tripId, data } = props ?? {};

    return expensesControllerCreate(tripId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesControllerCreate>>
>;
export type ExpensesControllerCreateMutationBody = CreateExpenseDto;
export type ExpensesControllerCreateMutationError = unknown;

/**
 * @summary Add an expense to a trip
 */
export const useExpensesControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesControllerCreate>>,
      TError,
      { tripId: string; data: CreateExpenseDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesControllerCreate>>,
  TError,
  { tripId: string; data: CreateExpenseDto },
  TContext
> => {
  return useMutation(getExpensesControllerCreateMutationOptions(options), queryClient);
};

/**
 * @summary Get all expenses in a trip
 */
export const expensesControllerFindAll = (tripId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips/${tripId}/expenses`, method: 'GET', signal });
};

export const getExpensesControllerFindAllQueryKey = (tripId: string) => {
  return [`/api/v1/trips/${tripId}/expenses`] as const;
};

export const getExpensesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerFindAll>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesControllerFindAllQueryKey(tripId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesControllerFindAll>>> = ({
    signal,
  }) => expensesControllerFindAll(tripId, signal);

  return { queryKey, queryFn, enabled: !!tripId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesControllerFindAll>>
>;
export type ExpensesControllerFindAllQueryError = unknown;

export function useExpensesControllerFindAll<
  TData = Awaited<ReturnType<typeof expensesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof expensesControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpensesControllerFindAll<
  TData = Awaited<ReturnType<typeof expensesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof expensesControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpensesControllerFindAll<
  TData = Awaited<ReturnType<typeof expensesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all expenses in a trip
 */

export function useExpensesControllerFindAll<
  TData = Awaited<ReturnType<typeof expensesControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getExpensesControllerFindAllQueryOptions(tripId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get expenses summary by category (for dashboard)
 */
export const expensesControllerGetSummary = (tripId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/expenses/summary`,
    method: 'GET',
    signal,
  });
};

export const getExpensesControllerGetSummaryQueryKey = (tripId: string) => {
  return [`/api/v1/trips/${tripId}/expenses/summary`] as const;
};

export const getExpensesControllerGetSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof expensesControllerGetSummary>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerGetSummary>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getExpensesControllerGetSummaryQueryKey(tripId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof expensesControllerGetSummary>>> = ({
    signal,
  }) => expensesControllerGetSummary(tripId, signal);

  return { queryKey, queryFn, enabled: !!tripId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expensesControllerGetSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpensesControllerGetSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof expensesControllerGetSummary>>
>;
export type ExpensesControllerGetSummaryQueryError = unknown;

export function useExpensesControllerGetSummary<
  TData = Awaited<ReturnType<typeof expensesControllerGetSummary>>,
  TError = unknown,
>(
  tripId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerGetSummary>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesControllerGetSummary>>,
          TError,
          Awaited<ReturnType<typeof expensesControllerGetSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpensesControllerGetSummary<
  TData = Awaited<ReturnType<typeof expensesControllerGetSummary>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerGetSummary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expensesControllerGetSummary>>,
          TError,
          Awaited<ReturnType<typeof expensesControllerGetSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpensesControllerGetSummary<
  TData = Awaited<ReturnType<typeof expensesControllerGetSummary>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerGetSummary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get expenses summary by category (for dashboard)
 */

export function useExpensesControllerGetSummary<
  TData = Awaited<ReturnType<typeof expensesControllerGetSummary>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof expensesControllerGetSummary>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getExpensesControllerGetSummaryQueryOptions(tripId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete an expense
 */
export const expensesControllerRemove = (tripId: string, id: string, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/expenses/${id}`,
    method: 'DELETE',
    signal,
  });
};

export const getExpensesControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expensesControllerRemove>>,
    TError,
    { tripId: string; id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expensesControllerRemove>>,
  TError,
  { tripId: string; id: string },
  TContext
> => {
  const mutationKey = ['expensesControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expensesControllerRemove>>,
    { tripId: string; id: string }
  > = (props) => {
    const { tripId, id } = props ?? {};

    return expensesControllerRemove(tripId, id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpensesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof expensesControllerRemove>>
>;

export type ExpensesControllerRemoveMutationError = unknown;

/**
 * @summary Delete an expense
 */
export const useExpensesControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expensesControllerRemove>>,
      TError,
      { tripId: string; id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expensesControllerRemove>>,
  TError,
  { tripId: string; id: string },
  TContext
> => {
  return useMutation(getExpensesControllerRemoveMutationOptions(options), queryClient);
};

/**
 * @summary Invite a user to the trip by email (owner only)
 */
export const membersControllerInvite = (
  tripId: string,
  inviteMemberDto: InviteMemberDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/members`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: inviteMemberDto,
    signal,
  });
};

export const getMembersControllerInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerInvite>>,
    TError,
    { tripId: string; data: InviteMemberDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerInvite>>,
  TError,
  { tripId: string; data: InviteMemberDto },
  TContext
> => {
  const mutationKey = ['membersControllerInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerInvite>>,
    { tripId: string; data: InviteMemberDto }
  > = (props) => {
    const { tripId, data } = props ?? {};

    return membersControllerInvite(tripId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerInvite>>
>;
export type MembersControllerInviteMutationBody = InviteMemberDto;
export type MembersControllerInviteMutationError = unknown;

/**
 * @summary Invite a user to the trip by email (owner only)
 */
export const useMembersControllerInvite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerInvite>>,
      TError,
      { tripId: string; data: InviteMemberDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerInvite>>,
  TError,
  { tripId: string; data: InviteMemberDto },
  TContext
> => {
  return useMutation(getMembersControllerInviteMutationOptions(options), queryClient);
};

/**
 * @summary List all members of a trip
 */
export const membersControllerFindAll = (tripId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({ url: `/api/v1/trips/${tripId}/members`, method: 'GET', signal });
};

export const getMembersControllerFindAllQueryKey = (tripId: string) => {
  return [`/api/v1/trips/${tripId}/members`] as const;
};

export const getMembersControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof membersControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerFindAll>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMembersControllerFindAllQueryKey(tripId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof membersControllerFindAll>>> = ({
    signal,
  }) => membersControllerFindAll(tripId, signal);

  return { queryKey, queryFn, enabled: !!tripId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof membersControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MembersControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerFindAll>>
>;
export type MembersControllerFindAllQueryError = unknown;

export function useMembersControllerFindAll<
  TData = Awaited<ReturnType<typeof membersControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof membersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersControllerFindAll<
  TData = Awaited<ReturnType<typeof membersControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof membersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersControllerFindAll<
  TData = Awaited<ReturnType<typeof membersControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all members of a trip
 */

export function useMembersControllerFindAll<
  TData = Awaited<ReturnType<typeof membersControllerFindAll>>,
  TError = unknown,
>(
  tripId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMembersControllerFindAllQueryOptions(tripId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Leave the trip (viewer only)
 */
export const membersControllerLeave = (tripId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/members/me`,
    method: 'DELETE',
    signal,
  });
};

export const getMembersControllerLeaveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerLeave>>,
    TError,
    { tripId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerLeave>>,
  TError,
  { tripId: string },
  TContext
> => {
  const mutationKey = ['membersControllerLeave'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerLeave>>,
    { tripId: string }
  > = (props) => {
    const { tripId } = props ?? {};

    return membersControllerLeave(tripId);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerLeaveMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerLeave>>
>;

export type MembersControllerLeaveMutationError = unknown;

/**
 * @summary Leave the trip (viewer only)
 */
export const useMembersControllerLeave = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerLeave>>,
      TError,
      { tripId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerLeave>>,
  TError,
  { tripId: string },
  TContext
> => {
  return useMutation(getMembersControllerLeaveMutationOptions(options), queryClient);
};

/**
 * @summary Change a member role (owner only)
 */
export const membersControllerUpdateRole = (
  tripId: string,
  memberId: string,
  updateMemberRoleDto: UpdateMemberRoleDto,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/members/${memberId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateMemberRoleDto,
    signal,
  });
};

export const getMembersControllerUpdateRoleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerUpdateRole>>,
    TError,
    { tripId: string; memberId: string; data: UpdateMemberRoleDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerUpdateRole>>,
  TError,
  { tripId: string; memberId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  const mutationKey = ['membersControllerUpdateRole'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerUpdateRole>>,
    { tripId: string; memberId: string; data: UpdateMemberRoleDto }
  > = (props) => {
    const { tripId, memberId, data } = props ?? {};

    return membersControllerUpdateRole(tripId, memberId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerUpdateRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerUpdateRole>>
>;
export type MembersControllerUpdateRoleMutationBody = UpdateMemberRoleDto;
export type MembersControllerUpdateRoleMutationError = unknown;

/**
 * @summary Change a member role (owner only)
 */
export const useMembersControllerUpdateRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerUpdateRole>>,
      TError,
      { tripId: string; memberId: string; data: UpdateMemberRoleDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerUpdateRole>>,
  TError,
  { tripId: string; memberId: string; data: UpdateMemberRoleDto },
  TContext
> => {
  return useMutation(getMembersControllerUpdateRoleMutationOptions(options), queryClient);
};

/**
 * @summary Remove a member from the trip (owner only)
 */
export const membersControllerRemove = (tripId: string, memberId: string, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/api/v1/trips/${tripId}/members/${memberId}`,
    method: 'DELETE',
    signal,
  });
};

export const getMembersControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerRemove>>,
    TError,
    { tripId: string; memberId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerRemove>>,
  TError,
  { tripId: string; memberId: string },
  TContext
> => {
  const mutationKey = ['membersControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerRemove>>,
    { tripId: string; memberId: string }
  > = (props) => {
    const { tripId, memberId } = props ?? {};

    return membersControllerRemove(tripId, memberId);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerRemove>>
>;

export type MembersControllerRemoveMutationError = unknown;

/**
 * @summary Remove a member from the trip (owner only)
 */
export const useMembersControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerRemove>>,
      TError,
      { tripId: string; memberId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerRemove>>,
  TError,
  { tripId: string; memberId: string },
  TContext
> => {
  return useMutation(getMembersControllerRemoveMutationOptions(options), queryClient);
};
